# Training parameters
train_params:
  debug: True
  seed: 42 # set to null to ignore fixing seed
  epochs: 50
  device: cuda # device name, values: "cpu" or "cuda:x" where 'x' is gpu index, or "cuda:a" to use all GPUs
  optimizer: adamw
  save_every: 5
  grad_clipping: 1.0 # set to zero to disable grad clipping
  start_saving_best: 5 # start epoch of saving best model
  compile: False # compile the model (requires PyTorch > 2.0)
  accumulation_steps: 1

# Logger parameters
logger:
  workspace: general # workspace name
  project: vertiformer # project name
  experiment_name: dt # name of the experiment
  tags: "ae train"
  resume: False # (boolean) whether to resume training or not
  online: True # (boolean) whether to store logs online or not
  experiment_key: "" # can be retrieved from logger dashboard, available if only resuming
  offline_directory: ./logs # where to store log data
  disabled: False # disable the comet ml
  upload_model: False # upload the model to CometML
  log_env_details: False # log virtual environment details
  auto_histogram_weight_logging: True # allows you to enable/disable histogram logging for biases and weights
  auto_histogram_gradient_logging: True # allows you to enable/disable automatic histogram logging of gradients
  auto_histogram_activation_logging: True # allows you to enable/disable automatic histogram logging of activations


# Dataloader parameters
dataloader:
  num_workers: 8 # Allowing multi-processing
  batch_size: 128
  shuffle: True # whether to shuffle data or not
  pin_memory: True # use pageable memory or pinned memory (https://developer.nvidia.com/blog/how-optimize-data-transfers-cuda-cc/)
  drop_last: True
 prefetch_factor: 2

# Train dataset parameters
dataset:
  root: vertiformer/data/train/data_train.pickle # where data resides
  train: True # train data
  f_size: 7 # filter size to smooth cmd
  height_diff: 0.5 # difference between min and max height with respect to robot
  stats: vertiformer/data/train/stats.pkl
  block_size: 6 # block size for the transformer
  data_frequency: 10 # actual data frequency in hz
  model_frequency: 3 # model frequency in hz
  obs_len: 2 # observation window in seconds
  pred_len: 6 # prediction length into the future
  resize: 16
  task: fkd # downstream task. Options: ['fkd', 'bc', 'reconstruction', 'ikd']

# Validation dataset parameters/ only change parameters that are different from train data
val_dataset:
  train: False # val data
  root: vertiformer/data/val/data_val.pickle
  task: ${dataset.task} # downstream task. Options: ['fkd', 'bc', 'reconstruction', 'ikd']

# directories
directory:
  model_name: model-name # file name for saved model. To be set automatically, no need to change
  save: vertiformer/checkpoint
  load: vertiformer/checkpoint/model-name-best.pt

# model parameters
model:
  finetune: False
  transformer: ${from_yaml:vertiformer/conf/vertiencoder.yaml, model} # get the 'model' info from the transformer config
  transformer_weight: vertiformer/checkpoint/exp-E300.tar
  bc_model: ${from_yaml:vertiformer/conf/bc_model.yaml, model}
  fkd_model: ${from_yaml:vertiformer/conf/fkd_model.yaml, model}
  ikd_model: ${from_yaml:vertiformer/conf/ikd_model.yaml, model}
  action_encoder:
    latent_dim: ${model.transformer.action_encoder.latent_dim}
    in_dim: ${model.transformer.action_encoder.in_dim}

# AdamW parameters if using Adam optimizer
adamw:
  lr: 5e-3
  betas:
    - 0.9
    - 0.999
  eps: 1e-6
  weight_decay: 0.05
  amsgrad: False
  fused: True

# Adam parameters if using Adam optimizer
adam:
  lr: 5e-4
  betas:
    - 0.9
    - 0.999
  eps: 1e-8
  weight_decay: 0
  amsgrad: False

# RMSprop parameters if using RMSprop optimizer
rmsprop:
  lr: 1e-3
  momentum: 0
  alpha: 0.99
  eps: 1e-8
  centered: False
  weight_decay: 0

# SGD parameters if using SGD optimizer
sgd:
  lr: 1e-3
  momentum: 0 # momentum factor
  weight_decay: 0 # weight decay (L2 penalty)
  dampening: 0 # dampening for momentum
  nesterov: False # enables Nesterov momentum
